# Site settings
title: Eduardo L. Martinez
email: elmartinez85@gmail.com
description: >
  Personal site and technical blog for Eduardo L. Martinez.
  Here you'll find posts about software development and a place
  to keep my resume and other professional information.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://eduardolmartinez.com" # the base hostname & protocol for your site
twitter_username: elmartinez85
github_username:  elmartinez85

# Build settings
markdown: kramdown
